site:
  title: Docs
  url: https://docs.tigergraph.com/
  start_page: home::index.adoc
  robots: |
    User-agent: *
    Sitemap: https://docs.tigergraph.com/sitemap.xml
content:
  sources:
  - url: https://github.com/tigergraph/data360-docs.git
    branches: [main]
ui:
  bundle:
    url: https://github.com/tigergraph/antora-ui/blob/main/build/ui-bundle.zip?raw=true
    # url: /Users/lenny.chen/Documents/migration/antora-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  extensions:
  - ./libs/tabs-block.js
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
  redirect_facility: netlify