site:
  title: Docs
  url: https://docs.tigergraph.com/
  start_page: home::index.adoc
  robots: |
    User-agent: *
    Sitemap: https://docs.tigergraph.com/sitemap.xml
content:
  sources:
  - url: https://github.com/tigergraph/doc-site.git
    branches: [main]
    start_paths: home
  - url: https://github.com/tigergraph/server-docs.git
    branches: [main, 3.3]
  - url: https://github.com/tigergraph/gui-docs.git
    branches: [main, 3.3]
  - url: https://github.com/tigergraph/cloud-docs.git
    branches: main
  - url: https://github.com/tigergraph/tigdsl-docs.git
    branches: main
  - url: https://github.com/tigergraph/gsql-docs.git
    branches: [main, 3.3]
  - url: https://github.com/lennessyy/tigergraphql.git
    branches: [main]
ui:
  bundle:
    url: https://github.com/tigergraph/antora-ui/blob/main/build/ui-bundle.zip?raw=true
    # url: /Users/lenny.chen/Documents/migration/antora-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    page-component-order: '!home, cloud, tigergraph-server, gsql-ref, gui, graph-ml, graphql'
  extensions:
  - ./libs/tabs-block.js
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:from
  latest_version_segment: current
  redirect_facility: netlify