site:
  title: Docs
  url: https://serene-mclean-f91eb7.netlify.app/
  start_page: tigergraph-server:intro:introduction.adoc
content:
  sources:
  - url: https://github.com/lennessyy/tg-server.git
    branches: main
  - url: https://github.com/lennessyy/tg-gui.git
    branches: [main, 3.3]
  - url: https://github.com/lennessyy/cloud.git
    branches: main
  - url: https://github.com/lennessyy/graph-ml.git
    branches: main
  - url: https://github.com/lennessyy/gsql.git
    branches: main
ui:
  bundle:
    url: https://github.com/lennessyy/antora-ui/blob/main/build/ui-bundle.zip?raw=true
    # url: /Users/lenny.chen/Documents/migration/antora-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
  - ./libs/tabs-block.js
urls:
  html_extension_style: drop
