[build]

    publish = "build/site/"
    command = "npm run build"

# redirects for gui
[[redirects]]
    from = "/ui/graphstudio"
    to = "/gui/current"

[[redirects]]
    from = "/ui/admin-portal"
    to = "/gui/current/admin-portal/overview"

[[redirects]]
    from = "/ui/admin-portal/*"
    to = "/gui/current/admin-portal/:splat"

[[redirects]]
    from = "/ui/graphstudio/*"
    to = "/gui/current/graphstudio/:splat"

[[redirects]]
    from = "/tigergraph-cloud/tigergraph-cloud-faqs"
    to = "/cloud/support/faqs"

# redirects for cloud
[[redirects]]
    from = "/cloud/tigergraph-cloud-faqs"
    to = "/cloud/support/faqs"

# redirects for language reference
[[redirects]]
    from = "/dev/gsql-ref/querying/func"
    to = "/gsql-ref/current/querying/func/readme"

[[redirects]]
    from = "/dev/gsql-ref"
    to = "/gsql-ref/current/intro/intro"

[[redirects]]
    from = "/dev/gsql-ref/querying/select-statement"
    to = "/gsql-ref/current/querying/select-statement/readme"

[[redirects]]
    from = "/dev/gsql-ref/*"
    to = "/gsql-ref/current/:splat"

[[redirects]]
    from = "/start/gsql-101"
    to = "/gsql-ref/current/tutorials/gsql-101/readme"

[[redirects]]
    from = "/start/gsql-101/*"
    to = "/gsql-ref/current/tutorials/gsql-101/:splat"

[[redirects]]
    from = "/start/gsql-102"
    to = "/gsql-ref/current/tutorials/pattern-matching/readme"

[[redirects]]
    from = "/start/gsql-102/*"
    to = "/gsql-ref/current/tutorials/pattern-matching/:splat"

[[redirects]]
    from = "/start/accumulators-tutorial"
    to = "/gsql-ref/current/tutorials/accumulators-tutorial"

# redirects for server
[[redirects]]
    from = "/dev/restpp-api"
    to = "/tigergraph-server/current/api/intro"

[[redirects]]
    from = "/start/get-started/*"
    to = "/tigergraph-server/current/getting-started/:splat"

[[redirects]]
    from = "/admin/admin-guide/system-management/management-with-gadmin"
    to = "/tigergraph-server/current/gadmin/management-with-gadmin"


[[redirects]]
    from = "/dev/restpp-api/*"
    to = "/tigergraph-server/current/api/:splat"

[[redirects]]
    from = "/admin/admin-guide/install-and-config/*"
    to = "/tigergraph-server/current/installation/:splat"

[[redirects]]
    from = "/admin/admin-guide/user-access/*"
    to = "/tigergraph-server/current/user-access/:splat"

[[redirects]]
    from = "/dev/using-a-remote-gsql-client "
    to = "/tigergraph-server/current/gsql-shell/using-a-remote-gsql-client"

[[redirects]]
    from = "/faq/change-log-1"
    to = "/tigergraph-server/current/release-notes/release-notes"

# redirects for graph-ml
[[redirects]]
    from = "/graph-algorithm-library"
    to = "/graph-ml/current/intro/overview"

[[redirects]]
    from = "/dev/data-loader-guides/*"
    to = "/tigergraph-server/current/data-loading/:splat"